version: "3"

services:

  front: 
    container_name: makeup4k_client
    image: node:10-alpine
    ports: 
        - "8000:8000"
    working_dir: /app
    volumes: 
        - ./:/app
    command: sh -c "npm install && npm run dev"
